services:
  valheim:
    platform: linux/amd64
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes:
      - $HOME/valheim-server/config:/config
      - $HOME/valheim-server/data:/opt/valheim
    ports:
      - "2456-2458:2456-2458/udp"
    environment:
      SERVER_NAME: "LM VH"
      WORLD_NAME: "Cornwall"
      SERVER_PASS: "change-this"
      SERVER_PUBLIC: "false"
    restart: always
    stop_grace_period: 2m

  php:
    platform: linux/amd64
    build: ./php
    restart: unless-stopped
    ports:
      - "9001:9000"
    volumes:
      - ./vhapi:/var/www/html
    networks:
      - lmvhn

  nginx:
    image: nginx:latest
    volumes:
      - ./vhapi:/vhapi
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    networks:
      - lmvhn
      
networks:
  lmvhn:
    driver: bridge
